name: Cypress Tests (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  cypress-docker:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:15.0.0
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Show Cypress info
        run: npx cypress info

      - name: Run Cypress tests (${{ matrix.browser }})
        run: |
           if [ "${{ matrix.browser }}" = "firefox" ]; then
              npx cypress run --browser firefox --headless --no-sandbox
          else
              npx cypress run --browser ${{ matrix.browser }} --headless
           fi

      - name: Upload Cypress screenshots (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots

      - name: Upload Cypress videos (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos
